# Generated by Django 4.2.4 on 2023-10-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_comment_request_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='category',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='subject',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='companyName',
            new_name='europeCountry',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
