# Generated by Django 4.2.4 on 2023-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_category_request_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
